<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<?php echo $this->tag->form(array('index/login', 'method' => 'post', 'style' => "display:none", 'id' => 'loginform')); ?>

	<p>
		<label for="name">Password</label>
		<?php echo $this->tag->passwordField("password") ?>
	</p>

	<p>
		<?php echo $this->tag->submitButton("Enter") ?>
	</p>

</form>

<script type="text/javascript">
	var id = localStorage.getItem('id');
	if(id==null)
		document.getElementById('loginform').style.display = 'block';
	else window.location.href = '/third-day/index/profile'
</script>

<a class="pushbullet-subscribe-widget" data-channel="daophan" data-widget="button" data-size="small"></a>
<script type="text/javascript">(function(){var a=document.createElement('script');a.type='text/javascript';a.async=true;a.src='https://widget.pushbullet.com/embed.js';var b=document.getElementsByTagName('script')[0];b.parentNode.insertBefore(a,b);})();</script>

</body>
</html>