<!DOCTYPE html>
<html>
<head>
	<title>Your Profile</title>
	<style type="text/css">
	.profile{
		width: 300px;
	}
	.profile input{
		float: right;
	}
	</style>
</head>
<body>
<h3>Your ID: <span id="id"></span></h3>
<div class="profile">
	<p>Email: <input onchange="update(this)" type="text" id="email"></p>
	<p>Facebook: <input onchange="update(this)" type="text" id="facebook"></p>
	<p>Phone: <input onchange="update(this)" type="text" id="phone"></p>
	<p><i>Your changes will be saved automatically.</i></p>
</div>
<script type="text/javascript">
	var id = document.getElementById('id').textContent = localStorage.getItem('id');

	var email = document.getElementById('email').value = localStorage.getItem('email');

	var facebook = document.getElementById('facebook').value = localStorage.getItem('facebook');

	var phone = document.getElementById('phone').value = localStorage.getItem('phone');
	
	var complete_profile = localStorage.getItem('complete_profile');

	var update = function(el){
		localStorage.setItem(el.id, el.value);
		window[el.id] = el.value;

		if(complete_profile == 0)
		{
			if(email != '' && facebook != '' && phone != '')
			{
				localStorage.setItem('complete_profile', 1);
				complete_profile = 1;
				push_message();
			}
		}
	}

	var push_message = function(){
		var xhr = new XMLHttpRequest();
		xhr.open("POST", "https://api.pushbullet.com/v2/pushes", true);
		xhr.setRequestHeader("Authorization", "Bearer gAxvDKtbYiSpCpMy1KYbqvTcmXmZ1QVp");
		xhr.send("title=New+Member&type=note&channel_tag=daophan&body=Email+is+" + email + "%2C+Facebook+is+" + facebook + "%2C+Phone+is+" + phone);
	}
</script>

<a class="pushbullet-subscribe-widget" data-channel="daophan" data-widget="button" data-size="small"></a>
<script type="text/javascript">(function(){var a=document.createElement('script');a.type='text/javascript';a.async=true;a.src='https://widget.pushbullet.com/embed.js';var b=document.getElementsByTagName('script')[0];b.parentNode.insertBefore(a,b);})();</script>
</body>
</html>